# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'typps' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for typps
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  pod 'FontAwesomeKit', '~> 2.2.0'

end
